<?php

namespace AppBundle\Repository;

/**
 * RandomizationIndexesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RandomizationIndexesRepository extends \Doctrine\ORM\EntityRepository
{
}
