<?php

namespace AppBundle\Repository;

/**
 * ToolReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
